### ISSUE TITLE
关于 `建立Licenses`

### ISSUE THREAD

**Issue by imknown** [xmagicj/HappyVolley#1]
先在 `Github` 创建仓库, 直接可以加一个 `License`.
`Clone` 到本地进行修改, 再 `Push` 回来.
:D

> https://github.com/xmagicj/HappyVolley#链接

**Comment by xmagicj** [comment]
感谢回复~

**Comment by imknown** [comment]
:D 客气, 我也是遇到 `volley` 坑, 搜到 `githuber 主` 的博客. 我决定放弃使用了 两年的 `Volley` 转 `retrofit 了`..

**Comment by xmagicj** [comment]
挺好的 与时俱进  用okHttp和Retrofit的确实更多

**Comment by imknown** [comment]
@xmagicj 是啊, `volley` 有点撑不住 公司项目了, `json` **超级** 大.. `iOS` 特别快, `andorid` 用 `volley` 慢的要死
